easyfinder/Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('divisions','Backend\DivisionController');
Route::resource('districts','Backend\DistrictController');
Route::resource('upazilas','Backend\UpazilaController');
Route::resource('unions','Backend\UnionController');
Route::resource('cities','Backend\CityController');
Route::resource('thanas','Backend\ThanaController');
Route::resource('wards','Backend\WardController');

Route::group(['prefix'=>'categories'],function(){

    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

});
Route::group(['prefix'=>'/bechelors'],function(){

//bechelors route details
Route::get('/',"Backend\BechelorController@index")->name('bechelors.index');
Route::get('/create',"Backend\BechelorController@create")->name('bechelors.create');
Route::post('/store',"Backend\BechelorController@store")->name('bechelors.store');
Route::get('/show/{id}',"Backend\BechelorController@show")->name('bechelors.show');
Route::get('/edit/{id}',"Backend\BechelorController@edit")->name('bechelors.edit');
Route::post('/update/{id}',"Backend\BechelorController@update")->name('bechelors.update');
Route::post('/delete/{id}',"Backend\BechelorController@delete")->name('bechelors.delete');

});
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });

easyfinder/Easyfinder/app/Http/Controllers/Backend/WardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Ward;
use App\Backend\Thana;

class WardController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      $wards =Ward::orderBy('id','desc')->get();
      return view('Backend.admin.wards.index',compact('wards'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      $thanas =Thana::orderBy('id','desc')->get();
      return view('Backend.admin.wards.create',compact('thanas'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $this->validate($request,[
        'name'=>'required|max:50|min:5',
      ]);

      $wards=new Ward();
      $wards->name=$request->name;
      $wards->bangla_name=$request->bangla_name;
      $wards->latitude=$request->latitude;
      $wards->longitude=$request->longitude;
      $wards->thana_id=$request->thana_id;
      //dd($wards);
      $wards->save();
      if(!is_null($wards)){
        session()->flash('success','Ward create Successfully!!');
        return redirect()->route('wards.index');
      }else{
        session()->flash('success','Some Error Occer!!');
        return back();
      }

  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
       $wards=Ward::findOrFail($id);
       //dd($wards);
       return view('Backend.admin.wards.show',compact('wards'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      $thanas =Thana::orderBy('id','desc')->get();
      $wards = Ward::findOrFail($id);
      return view('Backend.admin.wards.edit',compact('thanas','wards'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
        //dd($id);
        $this->validate($request,[
          'name'=>'required|max:50|min:5',
          'thana_id'=>'required',
        ]);

        $wards=Ward::findOrFail($id);
        $wards->name=$request->name;
        $wards->bangla_name=$request->bangla_name;
        $wards->latitude=$request->latitude;
        $wards->longitude=$request->longitude;
        $wards->thana_id=$request->thana_id;
        $wards->update();
        if(!is_null($wards)){
            session()->flash('success','Ward Update Successfully!!');
            return redirect()->route('wards.index');
        }else{
            session()->flash('sticky_error','Some Error Occer!!');
            return back();
        }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      $wards=Ward::find($id);
      if(!is_null($wards))
      {
          $wards->delete();
          session()->flash('success','Product has delete Successfully');
          return back();
      }else{
          session()->flash('sticky_error','Some Error Occer');
          return back();
      }

  }
}

easyfinder/Easyfinder/resources/views/Backend/admin/wards/create.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
 		<div class="row ">
 			<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>City Create Form <span class="pull-right"><a href="{{ route('wards.index')}}">Back</a></span></h2>
        </div>
        <div class="card-body">
      <form method="POST" action="{{ route('wards.store') }}">
          @csrf
          <div class="form-group">
              <label for="latitude">Thana Name</label>
              <div class="form-input">
                  <select name="thana_id" class="form-control is-valid form-control-sm input-md" value="{{old('thana_id')}}">
                          <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
                          @foreach($thanas as $thana)
                          <option value="{{$thana->id}}">{{$thana->name}}</option>
                          @endforeach
                  </select>
                  <div class="valid-feedback">
                    {{ ($errors->has('thana_id')) ? $errors->first('thana_id') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="name">Ward Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Ward name" value="" required>
                  <div class="invalid-feedback">
                    {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="bangla_name">Ward Bangla Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter Ward Bangla Name" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="latitude">Ward Latitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" placeholder="Enter Ward latitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="longitude">Ward Longitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" placeholder="Enter Ward longitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                  </div>
              </div>
          </div>

          <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>

</div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/wards/edit.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="row">
        <div class="col-sm-8">
          <div class="card">
                <div class="card-header">
                  <h2>Thana Edit <span class="pull-right"><a href="{{ route('wards.index')}}">Back</a></span></h2>
                </div>
                 <div class="card-body">
                   <form method="POST" action="{{ route('wards.update',$wards->id) }}" >
                       @csrf
                       @method('PUT')

                       <div class="form-group">
                           <label for="latitude">City Name</label>
                           <div class="form-input">
                               <select name="thana_id" class="form-control is-valid form-control-sm input-md" value="{{old('thana_id')}}">
                                       <option value="0" disabled="true" selected="true">===Select Under City===</option>
                                       @foreach($thanas as $thana)
                                       <option value="{{$thana->id}}" {{ $thana->id == $wards->thana_id ? 'selected' : ''}}>{{$thana->name}}</option>
                                       @endforeach
                               </select>
                               <div class="valid-feedback">
                                 {{ ($errors->has('thana_id')) ? $errors->first('thana_id') : ''}}
                               </div>
                           </div>
                       </div>


                        <div class="form-group">
                            <label for="name">Thana Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $wards->name}}">
                                <div class="invalid-feedback">
                                  {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="bangla_name">Thana Bangla Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $wards->bangla_name? $wards->bangla_name:'N\A'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="latitude">Thana Latitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $wards->latitude? $wards->latitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="longitude">Thana Longitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $wards->longitude? $wards->longitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                  </div>
                </div>
              </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/wards/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="card-header mt-2">
        <h2>Ward List<span class="pull-right"><a href="{{ route('wards.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="wards" class="table table-bordered table-striped">
          <caption>List of wards</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Bangla name</th>
  						<th>Latitude</th>
              <th>Longitude</th>
              <th>Parent Thana Name</th>
              <th>Show Details</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($wards as $ward)
  						<td>{{ $a++ }}</td>
  						<td>{{ $ward->name }}</td>
  						<td>
  						    @if($ward->bangla_name)
                  <p>{{ $ward->bangla_name}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($ward->latitude)
                  <p>{{ $ward->latitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($ward->longitude)
                  <p>{{ $ward->longitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color:green">{{$ward->thana->name}}</td>
              <td>
                <a href="{{route('wards.show', $ward->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('wards.edit', $ward->id)}}" class="badge badge-warning">Edit</a>
                <a href="#" onclick="return confirm('are you sure')">
									<form class="pull-right form-inline" action="{{route('wards.destroy', $ward->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<button class="badge badge-danger" type="submit">Delete</button>
									</form>
								</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#wards').DataTable();
} );
</script>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/wards/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <h4>Ward Details<a href="{{route('wards.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-3">
                   <p>Name</p>
                   <p>Bangla Name</p>
                   <p>Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-9">
                   <p>City: {{$wards->thana->city->name}}, Thana: {{$wards->thana->name}}, Ward: {{$wards->name}} </p>
                   <p>{{$wards->bangla_name?$wards->bangla_name:'N\A'}} </p>
                   <p>{{$wards->latitude?$wards->latitude:'N\A'}} </p>
                   <p>{{$wards->longitude?$wards->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection