easyfinder/Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('divisions','Backend\DivisionController');
Route::resource('districts','Backend\DistrictController');
Route::resource('upazilas','Backend\UpazilaController');
Route::resource('unions','Backend\UnionController');
Route::resource('cities','Backend\CityController');
Route::resource('thanas','Backend\ThanaController');
Route::resource('wards','Backend\WardController');

Route::group(['prefix'=>'categories'],function(){

    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

});
Route::group(['prefix'=>'/bechelors'],function(){

//bechelors route details
Route::get('/',"Backend\BechelorController@index")->name('bechelors.index');
Route::get('/create',"Backend\BechelorController@create")->name('bechelors.create');
Route::post('/store',"Backend\BechelorController@store")->name('bechelors.store');
Route::get('/show/{id}',"Backend\BechelorController@show")->name('bechelors.show');
Route::get('/edit/{id}',"Backend\BechelorController@edit")->name('bechelors.edit');
Route::post('/update/{id}',"Backend\BechelorController@update")->name('bechelors.update');
Route::post('/delete/{id}',"Backend\BechelorController@delete")->name('bechelors.delete');

});
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });

easyfinder/Easyfinder/app/Http/Controllers/Backend/UnionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Union;
use App\Backend\Upazila;

class UnionController extends Controller
{
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $unions =Union::orderBy('id','desc')->get();
            return view('Backend.admin.unions.index',compact('unions'));
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            $upazilas =Upazila::orderBy('id','desc')->get();
            return view('Backend.admin.unions.create',compact('upazilas'));
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
            $this->validate($request,[
              'name'=>'required|max:50|min:5',
            ]);

            $unions=new Union();
            $unions->name=$request->name;
            $unions->bangla_name=$request->bangla_name;
            $unions->latitude=$request->latitude;
            $unions->longitude=$request->longitude;
            $unions->upazila_id=$request->upazila_id;
            //dd($unions);
            $unions->save();
            if(!is_null($unions)){
              session()->flash('success','Union create Successfully!!');
              return redirect()->route('unions.index');
            }else{
              session()->flash('success','Some Error Occer!!');
              return back();
            }

        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
             $unions=Union::findOrFail($id);
             //dd($unions);
             return view('Backend.admin.unions.show',compact('unions'));
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            $upazilas =Upazila::orderBy('id','desc')->get();
            $unions = Union::findOrFail($id);
            return view('Backend.admin.unions.edit',compact('upazilas','unions'));
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $id)
        {
              //dd($id);
              $this->validate($request,[
                'name'=>'required|max:50|min:5',
                'upazila_id'=>'required',
              ]);

              $unions=Union::findOrFail($id);
              $unions->name=$request->name;
              $unions->bangla_name=$request->bangla_name;
              $unions->latitude=$request->latitude;
              $unions->longitude=$request->longitude;
              $unions->upazila_id=$request->upazila_id;
              $unions->update();
              if(!is_null($unions)){
                  session()->flash('success','Union Update Successfully!!');
                  return redirect()->route('unions.index');
              }else{
                  session()->flash('sticky_error','Some Error Occer!!');
                  return back();
              }
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            $unions=Union::find($id);
            if(!is_null($unions))
            {
                $unions->delete();
                session()->flash('success','Product has delete Successfully');
                return back();
            }else{
                session()->flash('sticky_error','Some Error Occer');
                return back();
            }

        }
}

easyfinder/Easyfinder/resources/views/Backend/admin/unions/create.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
 		<div class="row ">
 			<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>Union Create Form <span class="pull-right"><a href="{{ route('unions.index')}}">Back</a></span></h2>
        </div>
        <div class="card-body">
      <form method="POST" action="{{ route('unions.store') }}">
          @csrf
          <div class="form-group">
              <label for="latitude">Upazila Name</label>
              <div class="form-input">
                  <select name="upazila_id" class="form-control is-valid form-control-sm input-md" value="{{old('thana_id')}}">
                          <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
                          @foreach($upazilas as $upazila)
                          <option value="{{$upazila->id}}">{{$upazila->name}}</option>
                          @endforeach
                  </select>
                  <div class="valid-feedback">
                    {{ ($errors->has('upazila_id')) ? $errors->first('upazila_id') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="name">Union Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Union name" value="" required>
                  <div class="invalid-feedback">
                    {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="bangla_name">Union Bangla Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter Union Bangla Name" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="latitude">Union Latitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" placeholder="Enter Union latitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="longitude">Union Longitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" placeholder="Enter Union longitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                  </div>
              </div>
          </div>

          <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>

</div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/unions/edit.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="row">
        <div class="col-sm-8">
          <div class="card">
                <div class="card-header">
                  <h2>Union Edit <span class="pull-right"><a href="{{ route('unions.index')}}">Back</a></span></h2>
                </div>
                 <div class="card-body">
                   <form method="POST" action="{{ route('unions.update',$unions->id) }}" >
                       @csrf
                       @method('PUT')

                       <div class="form-group">
                           <label for="latitude">Upazila Name</label>
                           <div class="form-input">
                               <select name="upazila_id" class="form-control is-valid form-control-sm input-md" value="{{old('city_id')}}">
                                       <option value="0" disabled="true" selected="true">===Select Under City===</option>
                                       @foreach($upazilas as $upazila)
                                       <option value="{{$upazila->id}}" {{ $upazila->id == $unions->upazila_id ? 'selected' : ''}}>{{$upazila->name}}</option>
                                       @endforeach
                               </select>
                               <div class="valid-feedback">
                                 {{ ($errors->has('upazila_id')) ? $errors->first('upazila_id') : ''}}
                               </div>
                           </div>
                       </div>


                        <div class="form-group">
                            <label for="name">Union Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $unions->name}}">
                                <div class="invalid-feedback">
                                  {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="bangla_name">Union Bangla Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $unions->bangla_name? $unions->bangla_name:'N\A'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="latitude">Union Latitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $unions->latitude? $unions->latitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="longitude">Union Longitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $unions->longitude? $unions->longitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                  </div>
                </div>
              </div>
        <div class="col-sm-4">
          <div id="map">

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/unions/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="card-header mt-2">
        <h2>Union List<span class="pull-right"><a href="{{ route('unions.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="unions" class="table table-bordered table-striped">
          <caption>List of unions</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Bangla name</th>
  						<th>Latitude</th>
              <th>Longitude</th>
              <th>Parent Union Name</th>
              <th>Show Details</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($unions as $union)
  						<td>{{ $a++ }}</td>
  						<td>{{ $union->name }}</td>
  						<td>
  						    @if($union->bangla_name)
                  <p>{{ $union->bangla_name}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($union->latitude)
                  <p>{{ $union->latitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($union->longitude)
                  <p>{{ $union->longitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color:green">{{$union->upazila->name}}</td>
              <td>
                <a href="{{route('unions.show', $union->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('unions.edit', $union->id)}}" class="badge badge-warning">Edit</a>
                <a href="#" onclick="return confirm('are you sure')">
									<form class="pull-right form-inline" action="{{route('unions.destroy', $union->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<button class="badge badge-danger" type="submit">Delete</button>
									</form>
								</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#unions').DataTable();
} );
</script>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/unions/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <h4>Uinon Details<a href="{{route('unions.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-4">
                   <p>Thana name</p>
                   <p>Thana Bangla Name</p>
                   <p>Thana Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-8">
                   <p>Division: {{$unions->upazila->name}}, Uinon: {{$unions->name}}</p>
                   <p>{{$unions->bangla_name?$unions->bangla_name:'N\A'}} </p>
                   <p>{{$unions->latitude?$unions->latitude:'N\A'}} </p>
                   <p>{{$unions->longitude?$unions->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
        </div>
        <div id="map">

        </div>
      </div>
    </div>
  </div>
</div>
@endsection