easyfinder/Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('divisions','Backend\DivisionController');
Route::resource('districts','Backend\DistrictController');
Route::resource('upazilas','Backend\UpazilaController');
Route::resource('unions','Backend\UnionController');
Route::resource('cities','Backend\CityController');
Route::resource('thanas','Backend\ThanaController');
Route::resource('wards','Backend\WardController');

Route::group(['prefix'=>'categories'],function(){

    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

});
Route::group(['prefix'=>'/bechelors'],function(){

//bechelors route details
Route::get('/',"Backend\BechelorController@index")->name('bechelors.index');
Route::get('/create',"Backend\BechelorController@create")->name('bechelors.create');
Route::post('/store',"Backend\BechelorController@store")->name('bechelors.store');
Route::get('/show/{id}',"Backend\BechelorController@show")->name('bechelors.show');
Route::get('/edit/{id}',"Backend\BechelorController@edit")->name('bechelors.edit');
Route::post('/update/{id}',"Backend\BechelorController@update")->name('bechelors.update');
Route::post('/delete/{id}',"Backend\BechelorController@delete")->name('bechelors.delete');

});
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });

easyfinder/Easyfinder/app/Http/Controllers/Backend/UpazilaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Upazila;
use App\Backend\District;

class UpazilaController extends Controller
{
      /**
       * Display a listing of the resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function index()
      {
          $upazilas =Upazila::orderBy('id','desc')->get();
          return view('Backend.admin.upazilas.index',compact('upazilas'));
      }

      /**
       * Show the form for creating a new resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function create()
      {
          $districts =District::orderBy('id','desc')->get();
          return view('Backend.admin.upazilas.create',compact('districts'));
      }

      /**
       * Store a newly created resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @return \Illuminate\Http\Response
       */
      public function store(Request $request)
      {
          $this->validate($request,[
            'name'=>'required|max:50|min:5',
          ]);

          $upazilas=new Upazila();
          $upazilas->name=$request->name;
          $upazilas->bangla_name=$request->bangla_name;
          $upazilas->latitude=$request->latitude;
          $upazilas->longitude=$request->longitude;
          $upazilas->district_id=$request->district_id;
          //dd($upazilas);
          $upazilas->save();
          if(!is_null($upazilas)){
            session()->flash('success','Upazila create Successfully!!');
            return redirect()->route('upazilas.index');
          }else{
            session()->flash('success','Some Error Occer!!');
            return back();
          }

      }

      /**
       * Display the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function show($id)
      {
           $upazilas=Upazila::findOrFail($id);
           //dd($upazilas);
           return view('Backend.admin.upazilas.show',compact('upazilas'));
      }

      /**
       * Show the form for editing the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function edit($id)
      {
          $districts =District::orderBy('id','desc')->get();
          $upazilas = Upazila::findOrFail($id);
          return view('Backend.admin.upazilas.edit',compact('districts','upazilas'));
      }

      /**
       * Update the specified resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function update(Request $request, $id)
      {
            //dd($id);
            $this->validate($request,[
              'name'=>'required|max:50|min:5',
              'district_id'=>'required',
            ]);

            $upazilas=Upazila::findOrFail($id);
            $upazilas->name=$request->name;
            $upazilas->bangla_name=$request->bangla_name;
            $upazilas->latitude=$request->latitude;
            $upazilas->longitude=$request->longitude;
            $upazilas->district_id=$request->district_id;
            $upazilas->update();
            if(!is_null($upazilas)){
                session()->flash('success','Upazila Update Successfully!!');
                return redirect()->route('upazilas.index');
            }else{
                session()->flash('sticky_error','Some Error Occer!!');
                return back();
            }
      }

      /**
       * Remove the specified resource from storage.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function destroy($id)
      {
          $upazilas=Upazila::find($id);
          if(!is_null($upazilas))
          {
              $upazilas->delete();
              session()->flash('success','Product has delete Successfully');
              return back();
          }else{
              session()->flash('sticky_error','Some Error Occer');
              return back();
          }

      }
}

easyfinder/Easyfinder/resources/views/Backend/admin/upazilas/create.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
 		<div class="row ">
 			<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>Upazila Create Form <span class="pull-right"><a href="{{ route('upazilas.index')}}">Back</a></span></h2>
        </div>
        <div class="card-body">
      <form method="POST" action="{{ route('upazilas.store') }}">
          @csrf
          <div class="form-group">
              <label for="latitude">District Name</label>
              <div class="form-input">
                  <select name="district_id" class="form-control is-valid form-control-sm input-md" value="{{old('thana_id')}}">
                          <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
                          @foreach($districts as $district)
                          <option value="{{$district->id}}">{{$district->name}}</option>
                          @endforeach
                  </select>
                  <div class="valid-feedback">
                    {{ ($errors->has('district_id')) ? $errors->first('district_id') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="name">Upazila Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Upazila name" value="" required>
                  <div class="invalid-feedback">
                    {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="bangla_name">Upazila Bangla Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter Upazila Bangla Name" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="latitude">Upazila Latitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" placeholder="Enter Upazila latitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="longitude">Upazila Longitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" placeholder="Enter Upazila longitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                  </div>
              </div>
          </div>

          <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>

</div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/upazilas/edit.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="row">
        <div class="col-sm-8">
          <div class="card">
                <div class="card-header">
                  <h2>Upazila Edit <span class="pull-right"><a href="{{ route('upazilas.index')}}">Back</a></span></h2>
                </div>
                 <div class="card-body">
                   <form method="POST" action="{{ route('upazilas.update',$upazilas->id) }}" >
                       @csrf
                       @method('PUT')

                       <div class="form-group">
                           <label for="latitude">Dirstrict Name</label>
                           <div class="form-input">
                               <select name="district_id" class="form-control is-valid form-control-sm input-md" value="{{old('city_id')}}">
                                       <option value="0" disabled="true" selected="true">===Select Under City===</option>
                                       @foreach($districts as $district)
                                       <option value="{{$district->id}}" {{ $district->id == $upazilas->district_id ? 'selected' : ''}}>{{$district->name}}</option>
                                       @endforeach
                               </select>
                               <div class="valid-feedback">
                                 {{ ($errors->has('district_id')) ? $errors->first('district_id') : ''}}
                               </div>
                           </div>
                       </div>


                        <div class="form-group">
                            <label for="name">Upazila Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $upazilas->name}}">
                                <div class="invalid-feedback">
                                  {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="bangla_name">Upazila Bangla Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $upazilas->bangla_name? $upazilas->bangla_name:'N\A'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="latitude">Upazila Latitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $upazilas->latitude? $upazilas->latitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="longitude">Upazila Longitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $upazilas->longitude? $upazilas->longitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                  </div>
                </div>
              </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
  
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/upazilas/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="card-header mt-2">
        <h2>Upazila List<span class="pull-right"><a href="{{ route('upazilas.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="upazilas" class="table table-bordered table-striped">
          <caption>List of upazilas</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Bangla name</th>
  						<th>Latitude</th>
              <th>Longitude</th>
              <th>Parent Upazila Name</th>
              <th>Show Details</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($upazilas as $upazila)
  						<td>{{ $a++ }}</td>
  						<td>{{ $upazila->name }}</td>
  						<td>
  						    @if($upazila->bangla_name)
                  <p>{{ $upazila->bangla_name}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($upazila->latitude)
                  <p>{{ $upazila->latitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($upazila->longitude)
                  <p>{{ $upazila->longitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color:green">{{$upazila->district->name}}</td>
              <td>
                <a href="{{route('upazilas.show', $upazila->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('upazilas.edit', $upazila->id)}}" class="badge badge-warning">Edit</a>
                <a href="#" onclick="return confirm('are you sure')">
									<form class="pull-right form-inline" action="{{route('upazilas.destroy', $upazila->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<button class="badge badge-danger" type="submit">Delete</button>
									</form>
								</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#upazilas').DataTable();
} );
</script>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/upazilas/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <h4>Upazila Details<a href="{{route('upazilas.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-4">
                   <p>Upazila name</p>
                   <p>Upazila Bangla Name</p>
                   <p>Upazila Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-8">
                   <p>Division: {{$upazilas->district->name}}, Upazila: {{$upazilas->name}}</p>
                   <p>{{$upazilas->bangla_name?$upazilas->bangla_name:'N\A'}} </p>
                   <p>{{$upazilas->latitude?$upazilas->latitude:'N\A'}} </p>
                   <p>{{$upazilas->longitude?$upazilas->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">

          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection