easyfinder/Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('divisions','Backend\DivisionController');
Route::resource('districts','Backend\DistrictController');
Route::resource('upazilas','Backend\UpazilaController');
Route::resource('unions','Backend\UnionController');
Route::resource('cities','Backend\CityController');
Route::resource('thanas','Backend\ThanaController');
Route::resource('wards','Backend\WardController');

Route::group(['prefix'=>'categories'],function(){

    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

});
Route::group(['prefix'=>'/bechelors'],function(){

//bechelors route details
Route::get('/',"Backend\BechelorController@index")->name('bechelors.index');
Route::get('/create',"Backend\BechelorController@create")->name('bechelors.create');
Route::post('/store',"Backend\BechelorController@store")->name('bechelors.store');
Route::get('/show/{id}',"Backend\BechelorController@show")->name('bechelors.show');
Route::get('/edit/{id}',"Backend\BechelorController@edit")->name('bechelors.edit');
Route::post('/update/{id}',"Backend\BechelorController@update")->name('bechelors.update');
Route::post('/delete/{id}',"Backend\BechelorController@delete")->name('bechelors.delete');

});
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });
// Route::group(['prefix'=>'/divisions'],function(){
//
// //Division route details
// Route::get('/',"DivisionController@index")->name('divisions.index');
// Route::get('/create',"DivisionController@create")->name('divisions.create');
// Route::post('/store',"DivisionController@store")->name('divisions.store');
// Route::get('/show/{id}',"DivisionController@show")->name('divisions.show');
// Route::get('/edit/{id}',"DivisionController@edit")->name('divisions.edit');
// Route::post('/update/{id}',"DivisionController@update")->name('divisions.update');
// Route::post('/delete/{id}',"DivisionController@delete")->name('divisions.delete');
//
// });

easyfinder/Easyfinder/app/Http/Controllers/Backend/DistrictController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Division;
use App\Backend\District;

class DistrictController extends Controller
{
      /**
       * Display a listing of the resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function index()
      {
          $districts =District::orderBy('id','desc')->get();
          return view('Backend.admin.districts.index',compact('districts'));
      }

      /**
       * Show the form for creating a new resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function create()
      {
          $divisions =Division::orderBy('id','desc')->get();
          return view('Backend.admin.districts.create',compact('divisions'));
      }

      /**
       * Store a newly created resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @return \Illuminate\Http\Response
       */
      public function store(Request $request)
      {
          $this->validate($request,[
            'name'=>'required|max:50|min:5',
          ]);

          $districts=new District();
          $districts->name=$request->name;
          $districts->bangla_name=$request->bangla_name;
          $districts->latitude=$request->latitude;
          $districts->longitude=$request->longitude;
          $districts->division_id=$request->division_id;
          //dd($districts);
          $districts->save();
          if(!is_null($districts)){
            session()->flash('success','District create Successfully!!');
            return redirect()->route('districts.index');
          }else{
            session()->flash('success','Some Error Occer!!');
            return back();
          }

      }

      /**
       * Display the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function show($id)
      {
           $districts=District::findOrFail($id);
           //dd($districts);
           return view('Backend.admin.districts.show',compact('districts'));
      }

      /**
       * Show the form for editing the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function edit($id)
      {
          $divisions =Division::orderBy('id','desc')->get();
          $districts = District::findOrFail($id);
          return view('Backend.admin.districts.edit',compact('divisions','districts'));
      }

      /**
       * Update the specified resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function update(Request $request, $id)
      {
            //dd($id);
            $this->validate($request,[
              'name'=>'required|max:50|min:5',
              'division_id'=>'required',
            ]);

            $districts=District::findOrFail($id);
            $districts->name=$request->name;
            $districts->bangla_name=$request->bangla_name;
            $districts->latitude=$request->latitude;
            $districts->longitude=$request->longitude;
            $districts->division_id=$request->division_id;
            $districts->update();
            if(!is_null($districts)){
                session()->flash('success','District Update Successfully!!');
                return redirect()->route('districts.index');
            }else{
                session()->flash('sticky_error','Some Error Occer!!');
                return back();
            }
      }

      /**
       * Remove the specified resource from storage.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function destroy($id)
      {
          $districts=District::find($id);
          if(!is_null($districts))
          {
              $districts->delete();
              session()->flash('success','Product has delete Successfully');
              return back();
          }else{
              session()->flash('sticky_error','Some Error Occer');
              return back();
          }

      }
}

easyfinder/Easyfinder/resources/views/Backend/admin/districts/create.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
 		<div class="row ">
 			<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>District Create Form <span class="pull-right"><a href="{{ route('districts.index')}}">Back</a></span></h2>
        </div>
        <div class="card-body">
      <form method="POST" action="{{ route('districts.store') }}">
          @csrf
          <div class="form-group">
              <label for="latitude">Thana Name</label>
              <div class="form-input">
                  <select name="division_id" class="form-control is-valid form-control-sm input-md" value="{{old('thana_id')}}">
                          <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
                          @foreach($divisions as $division)
                          <option value="{{$division->id}}">{{$division->name}}</option>
                          @endforeach
                  </select>
                  <div class="valid-feedback">
                    {{ ($errors->has('division_id')) ? $errors->first('division_id') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="name">Ward Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Ward name" value="" required>
                  <div class="invalid-feedback">
                    {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="bangla_name">Ward Bangla Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter Ward Bangla Name" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="latitude">Ward Latitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" placeholder="Enter Ward latitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label for="longitude">Ward Longitude</label>
              <div class="form-input">
                  <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" placeholder="Enter Ward longitude" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                  </div>
              </div>
          </div>

          <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>

</div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/districts/edit.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="row">
        <div class="col-sm-8">
          <div class="card">
                <div class="card-header">
                  <h2>Dirstrict Edit <span class="pull-right"><a href="{{ route('districts.index')}}">Back</a></span></h2>
                </div>
                 <div class="card-body">
                   <form method="POST" action="{{ route('districts.update',$districts->id) }}" >
                       @csrf
                       @method('PUT')

                       <div class="form-group">
                           <label for="latitude">Division Name</label>
                           <div class="form-input">
                               <select name="division_id" class="form-control is-valid form-control-sm input-md" value="{{old('city_id')}}">
                                       <option value="0" disabled="true" selected="true">===Select Under City===</option>
                                       @foreach($divisions as $division)
                                       <option value="{{$division->id}}" {{ $division->id == $districts->division_id ? 'selected' : ''}}>{{$division->name}}</option>
                                       @endforeach
                               </select>
                               <div class="valid-feedback">
                                 {{ ($errors->has('division_id')) ? $errors->first('division_id') : ''}}
                               </div>
                           </div>
                       </div>


                        <div class="form-group">
                            <label for="name">Dirstrict Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $districts->name}}">
                                <div class="invalid-feedback">
                                  {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="bangla_name">Dirstrict Bangla Name</label>
                            <div class="form-input">
                                <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $districts->bangla_name? $districts->bangla_name:'N\A'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="latitude">Dirstrict Latitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $districts->latitude? $districts->latitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="longitude">Dirstrict Longitude</label>
                            <div class="form-input">
                                <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $districts->longitude? $districts->longitude:'0.00'}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                  </div>
                </div>
              </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/districts/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="card-header mt-2">
        <h2>District List<span class="pull-right"><a href="{{ route('districts.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="districts" class="table table-bordered table-striped">
          <caption>List of districts</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Bangla name</th>
  						<th>Latitude</th>
              <th>Longitude</th>
              <th>Parent District Name</th>
              <th>Show Details</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($districts as $district)
  						<td>{{ $a++ }}</td>
  						<td>{{ $district->name }}</td>
  						<td>
  						    @if($district->bangla_name)
                  <p>{{ $district->bangla_name}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($district->latitude)
                  <p>{{ $district->latitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($district->longitude)
                  <p>{{ $district->longitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color:green">{{$district->division->name}}</td>
              <td>
                <a href="{{route('districts.show', $district->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('districts.edit', $district->id)}}" class="badge badge-warning">Edit</a>
                <a href="#" onclick="return confirm('are you sure')">
									<form class="pull-right form-inline" action="{{route('districts.destroy', $district->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<button class="badge badge-danger" type="submit">Delete</button>
									</form>
								</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#districts').DataTable();
} );
</script>
@endsection

easyfinder/Easyfinder/resources/views/Backend/admin/districts/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <h4>District Details<a href="{{route('districts.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-4">
                   <p>Thana name</p>
                   <p>Thana Bangla Name</p>
                   <p>Thana Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-8">
                   <p>Division: {{$districts->division->name}}, District: {{$districts->name}}</p>
                   <p>{{$districts->bangla_name?$districts->bangla_name:'N\A'}} </p>
                   <p>{{$districts->latitude?$districts->latitude:'N\A'}} </p>
                   <p>{{$districts->longitude?$districts->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection